cv/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('info_perso.urls')),
    path('auth/',include('auth_app.urls'))
]+static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

info_perso/models.py
from django.core.validators import MaxValueValidator
from django.db import models
from django.contrib.auth.models import User
from django.utils.translation import gettext_lazy as _

# Create your models here.
from django.db import models

class ProfileImg(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True)
    photo = models.ImageField(upload_to='profile_cv/')


    def __str__(self) -> str:
        return self.photo.name
    # Dans ce modèle, nous avons écrasé la méthode  save()
    # pour supprimer l'image originale lorsqu'une nouvelle image est enregistrée
    def save(self, *args, **kwargs):
        if self.pk:
            original = ProfileImg.objects.get(pk=self.pk)
            if original.photo != self.photo:
                original.photo.delete(False)
        super().save(*args, **kwargs)

class ProfileTitle(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True)
    titre = models.CharField(max_length=240, verbose_name=_("Nom du profile"))
    profile = models.TextField("Profile",blank=True,null=True)
    
    def __str__(self):
        return f"{self.titre}"

class CV(models.Model):
    STATUT=[
        ("Celibataire","Celibataire"),
        ("Marié","Marié"),
        ('Divorcé',"Divorcé"),
    ]
    user = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True)
    nom = models.CharField("Nom",max_length=100,blank=True,null=True)
    prenom = models.CharField("prenom",max_length=100,blank=True,null=True)
    email = models.EmailField("Adresse Email",blank=True,null=True)
    telephone = models.CharField("Numero Telephone",max_length=50,blank=True,null=True)
    birth_date=models.DateField("Date de Naissance",blank=True,null=True)
    address = models.CharField("Adresse ",max_length=250,blank=True,null=True)
    status=models.CharField('Status matrimonial',max_length=250,blank=True,null=True,choices=STATUT)

    def __str__(self):
        return f"{self.nom} {self.prenom}"

class Experience(models.Model):
    user=models.ForeignKey(User,on_delete=models.CASCADE,blank=True,null=True)
    titre = models.CharField(max_length=200,null=True, blank=True)
    entreprise = models.CharField(max_length=200,null=True, blank=True)
    ville = models.CharField(max_length=200,null=True, blank=True)
    reference = models.CharField(max_length=200,null=True, blank=True)
    telephone_reference = models.CharField(max_length=200,null=True, blank=True)
    debut = models.DateField("date Debut",null=True, blank=True)
    fin = models.DateField("date fin",null=True, blank=True)
    description = models.TextField("description",null=True, blank=True)

    def __str__(self):
        return self.titre

class Formation(models.Model):
    user=models.ForeignKey(User,on_delete=models.CASCADE,blank=True,null=True)
    diplome = models.CharField("Diplome Obtenu",max_length=100,null=True, blank=True)
    ecole = models.CharField("Ecole ",max_length=100,null=True, blank=True)
    ville = models.CharField("ville",max_length=100,null=True, blank=True)
    debut = models.DateField("date de debut",null=True, blank=True)
    fin = models.DateField("date fin",null=True, blank=True)
    description = models.TextField("Description du diplome obtenu",null=True, blank=True)

    def __str__(self):
        return self.diplome


class Competences(models.Model):
    user=models.ForeignKey(User,on_delete=models.CASCADE,blank=True,null=True)
    competence = models.CharField(max_length=240)
    niveau = models.IntegerField(choices=[(i, str(i)) for i in range(0, 11)], verbose_name=_("Niveau"))

    def __str__(self):
        return self.competence

class Social(models.Model):
    SOCIAL=[
        ('whatsapp','Whatsapp'),
        ('facebook','Facebook'),
        ('lindln','Lindln'),
        ('instagram','Instagram'),
        ('twitter','Twitter'),
    ]
    user=models.ForeignKey(User,on_delete=models.CASCADE,blank=True,null=True)
    social = models.CharField(max_length=50,null=True,blank=True,choices=SOCIAL)
    link = models.CharField(max_length=240,null=True,blank=True)
   
    def __str__(self):
        return self.social


class Langue(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True)
    langue = models.CharField(max_length=100, verbose_name=_("langue"))
    niveau = models.IntegerField(choices=[(i, str(i)) for i in range(0, 11)], verbose_name=_("Niveau"))

    class Meta:
        verbose_name = _("Langue")
        verbose_name_plural = _("Langues")

    def __str__(self):
        return self.langue

class CentreInteret(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True)
    titre = models.CharField(max_length=100, verbose_name=_("Nom"))

    class Meta:
        verbose_name = _("Centre d'intérêt")
        verbose_name_plural = _("Centres d'intérêts")

    def __str__(self):
        return self.titre

templates/b.html
{% extends 'layout.html' %}{% load static %}{% load widget_tweaks %} {% block content %}
    <h1>bienvenu dans ma page d'enretrainement</h1>
    {{profile}}
  {% if profile %}
    <h2>OKAY</h2>
  {% else %}
  <h2>NOTOKAY</h2>
  {% endif %}
{% endblock %}

templates/brouillon.html
{% extends 'layout.html' %}{% load static %} {% block content %}
    <h4>bienvenu dans MOn Brouillon</h4>

{% load widget_tweaks %}


<div  class="d-none">
   Contenu de la div
</div>

<div class="d-flex">
   <div class="info_perso col-4">
       <form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="form-group">
        {{ form.photo.label_tag }}
        {{ form.photo }}
    </div>
    <button type="submit" class="btn btn-primary">Télécharger</button>
</form>

        <div class="cv-div mt-3"><button id="toggle-button-cv" class="btn btn-primary">
   <i class="fas fa-plus myIcon"></i> Afficher la div
</button>

        <div class="d-none" id="div-info-perso">
       <h4>Information personelle</h4>
    <form method="post"  enctype="multipart/form-data" id="info-perso-form">
  {% csrf_token %}
  <div class="form-group mt-2">
     {{ form.nom|attr:"class:form-control"|attr:"placeholder:Votre prénom" }}
  </div>
  <div class="form-group mt-2">
    {{ form.prenom|attr:"class:form-control"|attr:"placeholder:Votre nom de famille" }}
  </div>
  <div class="form-group mt-2">
    {{ form.email|attr:"class:form-control"|attr:"placeholder:Votre email" }}
  </div>
  <div class="form-group mt-2">
     {{ form.telephone|attr:"class:form-control"|attr:"placeholder:Votre numéro de téléphone" }}
  </div>
  <div class="form-group mt-2">
      {{ form.address|attr:"class:form-control"|attr:"placeholder:Votre adresse" }}
  </div>
  <div class="form-group mt-2">
      <div class="input-group date" id="{{ form.birth_date.id_for_label }}_picker">
      {{ form.birth_date|attr:"class:form-control"|attr:"type:date" }}
      <span class="input-group-addon">
        <span class="glyphicon glyphicon-calendar"></span>
      </span>
    </div>
  </div>
   <button type="submit" class="btn btn-primary mt-3">Enregistrer</button>
</form>

  </div>
</div>

        <div class="formation-div mt-3"><button id="toggle-button-formation" class="btn btn-primary">
   <i class="fas fa-plus myIcon"></i> Afficher la div
</button>

        <div class="d-none" id="div-info-formation">
       <h4>Formation</h4>
    <form method="post"  enctype="multipart/form-data" id="info-formation-form">
  {% csrf_token %}
  <div class="form-group mt-2">
     {{ formationForm.diplome|attr:"class:form-control"|attr:"placeholder:Diplome Obtenu" }}
  </div>
  <div class="form-group mt-2">
    {{ formationForm.ecole|attr:"class:form-control"|attr:"placeholder:Etablissement Obtention" }}
  </div>
  <div class="form-group mt-2">
    {{ formationForm.ville|attr:"class:form-control"|attr:"placeholder:Ville" }}
  </div>
  <div class="form-group mt-2">
     {{ formationForm.debut|attr:"class:form-control"|attr:"type:date" }}
  </div>
  <div class="form-group mt-2">
      {{ formationForm.fin|attr:"class:form-control"|attr:"type:date"}}
  </div>
        <div class="form-group mt-2">
      {{ formationForm.description|attr:"class:form-control"|attr:"placeholder:Description ou Commentaire" }}
  </div>


  <button type="submit" class="btn btn-primary mt-3">Enregistrer</button>
</form>

  </div>
        </div>
         <div class="experience-div mt-3"><button id="toggle-button-experience" class="btn btn-primary">
   <i class="fas fa-plus myIcon"></i> Afficher la div
</button>

        <div class="d-none" id="div-info-experience">
       <h4>Experience Profesionnelle</h4>
    <form method="post"  enctype="multipart/form-data" id="info-experience-form">
  {% csrf_token %}
  <div class="form-group mt-2">
     {{ experienceForm.titre|attr:"class:form-control"|attr:"placeholder:le Titre de votre experience" }}
  </div>
  <div class="form-group mt-2">
    {{ experienceForm.entreprise|attr:"class:form-control"|attr:"placeholder:Le nom de l'entreprise" }}
  </div>
  <div class="form-group mt-2">
    {{ experienceForm.ville|attr:"class:form-control"|attr:"placeholder: ville" }}
  </div>
  <div class="form-group mt-2">
     {{ experienceForm.debut|attr:"class:form-control"|attr:"type:date"}}
  </div>
  <div class="form-group mt-2">
      {{ experienceForm.fin|attr:"class:form-control"|attr:"type:date" }}
  </div>
        <div class="form-group mt-2">
      {{ experienceForm.description|attr:"class:form-control"|attr:"placeholder:la description de l'experience" }}
  </div>


  <button type="submit" class="btn btn-primary mt-3">Enregistrer</button>
</form>

  </div>
        </div>

       <div class="competence-div mt-3"><button id="toggle-button-competence" class="btn btn-primary">
   <i class="fas fa-plus myIcon"></i> Afficher la div
</button>

        <div class="d-none" id="div-info-competence">
       <h4>Formation</h4>
    <form method="post"  enctype="multipart/form-data" id="info-competence-form">
  {% csrf_token %}
  <div class="d-flex">
      <div class="form-group mt-2 col-9">
     {{ competenceForm.competence|attr:"class:form-control"|attr:"placeholder:Votre Competence" }}
  </div>
      <label for="niveau" class="mx-3">niveau</label>
  <div class="form-group mt-2 col-3">

    {{ competenceForm.niveau|attr:"class:form-control"|attr:"placeholder:Noter votre niveau" }}
  </div>
  </div>




  <button type="submit" class="btn btn-primary mt-3">Enregistrer</button>
</form>

  </div>
        </div>

        <div class="langue-div mt-3"><button id="toggle-button-langue" class="btn btn-primary">
   <i class="fas fa-plus myIcon"></i> Afficher la div
</button>

        <div class="d-none" id="div-info-langue">
       <h4>Langue</h4>
    <form method="post"  enctype="multipart/form-data" id="info-langue-form">
  {% csrf_token %}
  <div class="d-flex">
      <div class="form-group mt-2 col-9">
     {{ langueForm.langue|attr:"class:form-control"|attr:"placeholder:entree une langue" }}
  </div>
      <label for="niveau" class="mx-3">niveau</label>
  <div class="form-group mt-2 col-3">

    {{ langueForm.niveau|attr:"class:form-control" }}
  </div>
  </div>




  <button type="submit" class="btn btn-primary mt-3">Enregistrer</button>
</form>

  </div>
        </div>

        <div class="centreInteret-div mt-3"><button id="toggle-button-centreInteret" class="btn btn-primary">
   <i class="fas fa-plus myIcon"></i> Afficher la div
</button>

        <div class="d-none" id="div-info-centreInteret">
       <h4>Centre d'interet</h4>
    <form method="post"  enctype="multipart/form-data" id="info-centreInteret-form">
  {% csrf_token %}

      <div class="form-group mt-2 col-9">
     {{ centreInteretForm.titre|attr:"class:form-control"|attr:"placeholder:entree un centre d'interet" }}

  </div>




  <button type="submit" class="btn btn-primary mt-3">Enregistrer</button>
</form>

  </div>
        </div>

   </div>
   </div>


    <div class="col-8"></div>
</div>
<div class='contain-cv'>
  <h4>My cv</h4>
</div>


<script>
// Pour afficher et masquer la div information Personnelle
hideAndShowDiv('toggle-button-cv','div-info-perso')

// Pour afficher et masquer la div information Formation
hideAndShowDiv('toggle-button-formation','div-info-formation')

// Pour afficher et masquer la div information Experience
hideAndShowDiv('toggle-button-experience','div-info-experience')

// Pour afficher et masquer la div information Competences
hideAndShowDiv('toggle-button-competence','div-info-competence')

// Pour afficher et masquer la div des langue parlée et ecris
hideAndShowDiv('toggle-button-langue','div-info-langue')

// Pour afficher et masquer la div centre d'interet
hideAndShowDiv('toggle-button-centreInteret','div-info-centreInteret')


// On enregistre le formualaire des informations personnelles
 $('form').submit(function(event) {
        event.preventDefault();
        var form = $("#info-perso-form");
        $.ajax({
            type: form.attr('method'),
            //url: 'test',
            url: 'create',
            data: form.serialize()+'&action=createInfoPerso',

            success: function(response) {
                if (response.success) {
                    alert("successfuly");
                    form.reset();
                }
                if(response.exists){
                alert("Merci de modifier");}
                 if(response.errors) {
                    alert(response.errors);
                }
            }
        });
    });

// On enregistre le formualaire des informations sur les Formations
 $('form').submit(function(event) {
        event.preventDefault();
        var form = $('#info-formation-form');
        var formData = new FormData(form[0]);
        $.ajax({
            type: form.attr('method'),
            //url: 'test',
            url: 'create',
            data: form.serialize()+'&action=createInfoFormation',

            success: function(response) {
                if (response.success) {
                    alert("successfuly");
                    form[0].reset()
                }
                if(response.exists){
                alert("Merci de modifier");}
                 if(response.errors) {
                    alert(response.errors);
                }
            }
        });
    });

 // On enregistre le formualaire des informations sur les Expereineces
 $('form').submit(function(event) {
        event.preventDefault();
        var form = $('#info-experience-form');
        var formData = new FormData(form[0]);
        $.ajax({
            type: form.attr('method'),
            url: 'create',
            data: form.serialize()+'&action=createInfoExpenrience',

            success: function(response) {
                if (response.success) {
                    alert("successfuly");
                    form[0].reset()
                }
                if(response.exists){
                alert("Merci de modifier");}
                 if(response.errors) {
                    alert(response.errors);
                }
            }
        });
    });



// On enregistre le formualaire des informations sur les Competences
 $('form').submit(function(event) {
        event.preventDefault();
        var form = $('#info-competence-form');
        var formData = new FormData(form[0]);
        $.ajax({
            type: form.attr('method'),
            url: 'create',
            data: form.serialize()+'&action=createInfoCompetence',

            success: function(response) {
                if (response.success) {
                    alert("successfuly");
                    form[0].reset()
                }
                if(response.exists){
                alert("Merci de modifier");}
                 if(response.errors) {
                    alert(response.errors);
                }
            }
        });
    });


// On enregistre le formualaire des informations sur les Langue Parlées
 $('form').submit(function(event) {
        event.preventDefault();
        var form = $('#info-langue-form');
        var formData = new FormData(form[0]);
        $.ajax({
            type: form.attr('method'),
            url: 'create',
            data: form.serialize()+'&action=createInfoLangue',

            success: function(response) {
                if (response.success) {
                    alert("successfuly");
                    form[0].reset()
                }
                if(response.exists){
                alert("Merci de modifier");}
                 if(response.errors) {
                    alert(response.errors);
                }
            }
        });
    });


// On enregistre le formualaire des informations sur les centre d'interets
 $('form').submit(function(event) {
        event.preventDefault();
        var form = $('#info-centreInteret-form');
        var formData = new FormData(form[0]);
        $.ajax({
            type: form.attr('method'),
            url: 'create',
            data: form.serialize()+'&action=createInfoCentreInteret',

            success: function(response) {
                if (response.success) {
                    alert("successfuly");
                    form[0].reset()
                }
                if(response.exists){
                alert("Merci de modifier");}
                 if(response.errors) {
                    alert(response.errors);
                }
            }
        });
    });







// FONCTION AFFICHER ET MASQUER UNE DIV
function hideAndShowDiv(button_id,div_id) {
    var toggleButton = document.getElementById(button_id);
var myDiv = document.getElementById(div_id);
var toggleIcon = toggleButton.querySelector(".myIcon");

toggleButton.addEventListener("click", function() {
   if (myDiv.classList.contains("d-none")) {
      myDiv.classList.remove("d-none");
      toggleIcon.classList.remove("fa-plus");
      toggleIcon.classList.add("fa-minus");
      toggleButton.textContent = "Masquer la div";
   } else {
      myDiv.classList.add("d-none");
      toggleIcon.classList.remove("fa-minus");
      toggleIcon.classList.add("fa-plus");
      toggleButton.textContent = "Afficher la div";
   }
});
}

// Function pour afficher une masquer une div
function hideDiv(div_id){
    var myDiv = document.getElementById(div_id);
    var toggleIcon = toggleButton.querySelector(".myIcon");

      myDiv.classList.add("d-none");
      toggleIcon.classList.remove("fa-minus");
      toggleIcon.classList.add("fa-plus");
      toggleButton.textContent = "Afficher la div";
}

</script>

{% endblock %}

templates/competence_info.html
{% extends 'layout.html'%}{% load static%}{% load widget_tweaks %}

{% block content %}

<h3>Competence Page </h3>
<button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#staticCompetenceFormModal">
    NOUVELLE COMPETENCE
</button>


  
  <!-- Modal  For Creation Competence information-->
<div class="modal fade" id="staticCompetenceFormModal" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticCompetenceFormModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="staticCompetenceFormModalLabel">AJOUTEZ UNE COMPETENCE </h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="form">
      <div class="modal-body">
          
              <form method="post"  enctype="multipart/form-data" id="info-competence-form">
                  {% csrf_token %}
                  <div class="form-group mt-1">
                    <label for="titre">Competence</label>
                      {{ competenceForm.competence|attr:"class:form-control"|attr:"Titre Competence" }}
                  </div>
                  <div class="form-group mt-1">
                    <label for="entreprise">Note/10</label>
                    {{ competenceForm.niveau|attr:"class:form-control"|attr:"placeholder:Note sur 10"|attr:'class:text-center' }}
                  </div>
                  
                        </form>
            
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary" id="btn_create_competence_info">Enregistrer</button>
          
      </div>
  </div> 
    </div>
  </div>
</div>


<!-- Modal  For modification Competence information-->
<div class="modal fade" id="staticEditCompetenceFormModal" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticEditCompetenceFormModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="staticEditCompetenceFormModalLabel">AJOUTEZ UNE FORMATION </h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="form">
        <div class="modal-body">
                <form method="post"  enctype="multipart/form-data" id="edit-info-competence-form">
                    {% csrf_token %}
                    <div class="form-group mt-1">
                        <label for="titre">Titre du poste</label>
                        <input id="id_titre_competence_edit" class="form-control" type="text" name="competence" maxlength="240" placeholder="Competence">
                    </div>
                    <div class="form-group mt-1">
                        <label for="id_niveau">Note / 10</label>
                        <select name="niveau" required id="id_niveau_competence_edit"class="form-control">
                            <option value="" selected>---------</option>
                            <option value="0">0</option>
                            <option value="1">1</option>
                            <option value="2">2</option>
                            <option value="3">3</option>
                            <option value="4">4</option>
                            <option value="5">5</option>
                            <option value="6">6</option>
                            <option value="7">7</option>
                            <option value="8">8</option>
                            <option value="9">9</option>
                            <option value="10">10</option>
                        </select>
                       
                    </div>
                    
                    
                      
                      
                    
                    <input type="hidden" id="idEditCompetenceInfo" name="id">
                          </form>
              
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
          <button type="button" class="btn btn-primary" id="btn_edit_competence_info" >Modifier</button>
            
        </div>
    </div> 
      </div>
    </div>
</div>


<!-- Modal  For Delete One Competence information-->
<div class="modal fade" id="deleteCompetenceFormModal" tabindex="-1" aria-labelledby="deleteCompetenceFormModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="deleteCompetenceFormModalLabel">SUPPRIMER UNE EXPERIENCE</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          <h4 class="card-header">SOUHAITEZ VOUS SUPPRIMER CETTE ENREGISTREMENT</h4>
          <div>
            <input type="hidden" id="id_delete_competence_info">
          </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
          <button type="button" class="btn btn-danger" id="btn_delete_competence_info">Supprimer !</button>
        </div>
      </div>
    </div>
  </div>



<!-- AFFICHAGE DU RESPONSE JAVASCRIPT-- -->
<div class="competence_info_data col-6" id="competence_info_data">
    {% if competences %}
                    {% for competence in competences %}
                    <div class='d-flex'>
                        <div class='competence_data col-9 mx-2 me-3'>
                            <h6 class='card-header'>{{competence.competence}}</h6>
                            <div class='progress'>
                                <div class='progress-bar w-50 bg-success' role='progressbar' aria-valuenow='50' aria-valuemin='0' aria-valuemax='100'></div>
                            </div>
                        </div>
                        <div class='col-3 mt-4'>
                            <a href="" type='button' class='fa fa-edit mx-1 me-1 btn_edit_competence' data-id='{{competence.id}}' data-bs-target="#staticEditCompetenceFormModal"  data-bs-toggle="modal"></a>
                        <a href="" type='button' class='fa fa-trash text-danger mx-1 me-1 btn_delete_competence' data-id='{{competence.id}}' data-bs-toggle="modal"  data-bs-target="#deleteCompetenceFormModal"></a>
                        </div>
                    </div>
                    {% endfor %}
    {% endif %}
</div>




<script>
// EVENEMENT LORS DE LA CREATION D'UNE NOUVELLE INFO SUR L'EXPERIENCE PROFESSIONNELLE
    $('#btn_create_competence_info').on('click',(e)=>{
        e.preventDefault();
        var form= $('#info-competence-form');
        // On lance la requete ajax pour recuperer le formulaire
        $.ajax({
            url:'',
            type:'POST',
            data:form.serialize()+"&createCompetenceInfo=createCompetenceInfo",
            success:(r)=>{
                competences=r.competences
                printCompetenceDiv(competences);
                form[0].reset()
                $('#staticCompetenceFormModal').modal('hide');
            }
        });
    });
  
    // EVENEMENT LORQU'ON CLICK SUR LE FONT EDIT D'UNE FORMATION
    // EVENEMENT LORS DE LA CREATION D'UNE NOUVELLE INFO SUR LA FORMATION
    $('.btn_edit_competence').on('click',(e)=>{
        e.preventDefault();
        id_competence=e.currentTarget.dataset.id;
        let form =$('#edit-info-competence-form');
        $.ajax({
            url:'',
            type:'GET',
            data:'id_competence='+id_competence+'&fetchOnCompetence=fetchOnCompetence',
            success:(r)=>{ 
                data=r.competence[0]
                labelModal=document.getElementById('staticEditCompetenceFormModalLabel');
                // ON insert les données dans le formulaires
                
                labelModal.innerText='MODIFICATION EXPERIENCE N°:'+data.id;
                $('#id_titre_competence_edit').val(data.competence);
                $('#id_niveau_competence_edit').val(data.niveau);
               
                $('#idEditCompetenceInfo').val(data.id)
            }
        })
    });
  
    // EVENEMENT POUR ENREGISTRE LA MODIFICATION DANS LA TABLE
    $('#btn_edit_competence_info').on('click',(e)=>{
        e.preventDefault();
        form=$('#edit-info-competence-form');
        let myId=$('#idEditCompetenceInfo').val();
        var divResponse=document.getElementById('competence_info_data')
        $.ajax({
            url:'',
            type:'POST',
            data:form.serialize()+"&editCompetenceInfo=editCompetenceInfo",
            success:(r)=>{
                competences=r.competences;
                printCompetenceDiv(competences);
                $('#staticEditCompetenceFormModal').modal('hide');
            }
        })
  
    });
  
    // EVENEMENT POUR AFFICHER UN ENREGISTREMENT A SUPPRIMER (FORMATION)
    $('.btn_delete_competence').on('click',function(e){
        e.preventDefault();
        myId=e.currentTarget.dataset.id;
        labelModal=document.getElementById('deleteCompetenceFormModalLabel');
        $('#id_delete_competence_info').val(myId);
        
        // ON insert les données dans le formulaires       
        labelModal.innerText='SUPPRIMER COMPETENCE N°:'+myId;
        
    });
  
  // EVENEMENT POUR SUPPRIMER UN ENREGISTREMENT
   $('#btn_delete_competence_info').on('click',function(e){
        e.preventDefault();
        
        id_competence=$('#id_delete_competence_info').val();
        var divResponse=document.getElementById('competence_info_data');
  
       $.ajax({
        url:'',
        type:'GET',
        data:"id_competence="+id_competence+"&deleteOnCompetence=deleteOnCompetence",
        success:(r)=>{
            competences=r.competences
          printCompetenceDiv(competences);
          $('#deleteCompetenceFormModal').modal('hide');
              
        }
      });
        
    });
  
  // FUnction Pour afficher le contenu de la formation du sur la divResponse
    function printCompetenceDiv(data){
      var divResponse=document.getElementById('competence_info_data');
      divResponse.innerHTML="";
      content="";
      data.forEach((e)=>{
      content+="<div class='d-flex'>";
      content+="<div class='competence_data col-9 mx-2 me-3'>";
      content+="<h6 class='card-header'>"+e.competence+"</h6>";
      content+="<div class='progress'><div class='progress-bar w-50 bg-success' role='progressbar' aria-valuenow='50' aria-valuemin='0' aria-valuemax='100'></div>"
      content+="</div></div><div class='col-3 mt-4'>";

      content+="<a href='' type='button' class='fa fa-edit mx-1 me-1 btn_edit_competence' data-id='"+e.id+"' data-bs-target='#staticEditCompetenceFormModal' data-bs-toggle='modal'></a>"; 
      content+="<a href='' type='button' class='fa fa-trash text-danger mx-1 me-1 btn_delete_competence' data-id='"+e.id+"' data-bs-target='#deleteCompetenceFormModal' data-bs-toggle='modal'></a>"; 
      content+="</div></div>";               
  
      });
      
      divResponse.innerHTML=content;
    }
</script>


  {% endblock %}

templates/welcome.html

{% extends 'layout.html' %}{% load static %} {% block content %}
    <h1>bienvenu a page d'accueil</h1>
    {{experience}}
{% endblock %}